version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: express-jwt
    versions:
    - 0.1.3
  - dependency-name: jsonwebtoken
    versions:
    - 0.4.0
  - dependency-name: sanitize-html
    versions:
    - 1.4.2
  - dependency-name: unzipper
    versions:
    - 0.9.15
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: socket.io
    versions:
    - 4.0.0
  - dependency-name: html-entities
    versions:
    - 2.2.0
    - 2.3.0
    - 2.3.1
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.10
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 2.0.2
    - 2.1.0
    - 2.1.1
    - 3.0.0
    - 3.0.1
    - 4.0.0
  - dependency-name: ngx-spinner
    versions:
    - 11.0.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
